name: CI

on: [pull_request]
    

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    SKIP_ENV_VALIDATION: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Get npm cache directory
              id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
              run: |
                echo "npm-cache-dir=$(npm config get cache)" >> $GITHUB_OUTPUT

            - name: Setup cache
              uses: actions/cache@v3
              id: cache
              with:
                path: ${{ steps.npm-cache.outputs.npm_cache_dir }}
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Typecheck
              run: npm run type-check

            - name: Lint
              run: npm run lint
